config/routes.rb
Rails.application.routes.draw do

  root "users#index"

  resources :users, :todos
  get 'todos/new/:id' => 'todos#new', as: :new_todo_for_user

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def new
    @todo = Todo.new(user_id: params[:id])
  end

  def create
    @todo = Todo.create(todo_params)

    redirect_to user_path(id: @todo.user_id)
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)

    redirect_to user_path(id: @todo.user_id)
  end


  def destroy
    @todo = Todo.find(params[:id])
    @todo.delete

    redirect_to users_path
  end

  def todo_params
    params.require(:todo).permit(:name, :remarks, :status, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save

    redirect_to user_path(@user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to user_path(@user.id)
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all.order('name')
  end

  def destroy
    @user = User.find(params[:id])
    @user.delete

    redirect_to users_path
  end

  def user_params
    params.require(:user).permit(:name, :sex, :phone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TodoWithoutScaffold" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">TodoWithoutScaffold</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/todos/edit.html.erb
<%= form_for @todo, :url => todo_path(@todo.id) do |todo| %>

    <%= todo.hidden_field :user_id %>
    Name :  <%= todo.text_field :name  %> <br>
    Remarks  :  <%= todo.text_area :remarks  %>  <br>
    <%= todo.submit "Edit ToDo", :class => 'btn btn-small btn-warning' %>
    <%= link_to "Go back to Main Page", users_path, :class => 'btn btn-small btn-primary' %>

<% end %>

app/views/todos/new.html.erb
<%= form_for @todo, :url => todos_path do |todo| %>

            <%= todo.hidden_field :user_id %>
    Name :  <%= todo.text_field :name  %> <br>
    Remarks  :  <%= todo.text_area :remarks  %>  <br>
    <%= todo.hidden_field :status %>
    <br>
    <%= todo.submit "Create New ToDo", :class => 'btn btn-small btn-success' %>
    <%= link_to "Go back to Main Page", users_path, :class => 'btn btn-small btn-primary' %>

<% end %>

app/views/users/edit.html.erb
<%= form_for @user, :url => user_path(@user.id) do |user| %>

    Name :  <%= user.text_field :name  %> <br>
    Sex  :  <%= user.text_field :sex  %>  <br>
    Phone : <%= user.text_field :phone  %>    <br><br>
    <%= user.submit "Update User", :class => 'btn btn-small btn-warning' %>
    <%= link_to "Go back to Main Page", users_path, :class => 'btn btn-small btn-primary' %>

<% end %>

app/views/users/index.html.erb
<%= link_to "Create New User", new_user_path, :class => 'btn btn-small btn-success' %>
<hr>
<h4> Displaying Users </h4>

<head>
  <style>

      table, td, th
      {
          border:2px solid blue;
      }
      th
      {
          background-color: royalblue;
          color:white;
      }
      td, th
      {
          padding:5px;
      }
      tr:nth-child(even) {background-color: white}
      tr:nth-child(odd) {background-color: lightcyan}
  </style>
</head>

<body>
<table>
  <tr>
    <th>Name</th>
    <th>Sex</th>
    <th>Phone</th>
    <th> ACTION </th>
    <th> ACTION </th>

  </tr>

  <% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name.upcase, user_path(user.id) %></td>
    <td><%= user.sex.capitalize %></td>
    <td><%= user.phone %></td>
    <td> <%= link_to "EDIT", edit_user_path(user.id), :class => 'btn btn-mini btn-warning' %> </td>
     <td> <%= link_to "DELETE", user_path(user.id), method: :delete, :class => 'btn btn-mini btn-danger' %> </td>
  </tr>
  <% end %>
</table>
</body>

app/views/users/new.html.erb
<%= form_for @user, :url => users_path do |user| %>

    Name :  <%= user.text_field :name  %> <br>
    Sex  :  <%= user.text_field :sex  %>  <br>
    Phone : <%= user.text_field :phone  %>    <br><br>
    <%= user.submit "Create New User", :class => 'btn btn-small btn-success' %>
    <%= link_to "Go back to Main Page", users_path, :class => 'btn btn-small btn-primary' %>

<% end %>

app/views/users/show.html.erb
<%= link_to "CREATE New ToDo", new_todo_for_user_path(@user.id), :class => 'btn btn-small btn-success' %>
<%= link_to "Go back to Main Page", users_path, :class => 'btn btn-small btn-primary' %>
<h4>User Details: </h4>
    <%= @user.name.upcase %> <br>
   [ <small> <%= @user.sex.capitalize %> |
    <%= @user.phone %> </small>]     <br>
<hr>


<h4> To Do List: </h4>

<head>
  <style>
      table, td, th
      {
          border:2px solid blue;
      }
      th
      {
          background-color: royalblue;
          color:white;
      }
      td, th
      {
          padding:5px;
      }
      tr:nth-child(even) {background-color: white}
      tr:nth-child(odd) {background-color: lightcyan}
  </style>
</head>

<body>
<table>
  <tr>
    <th>Name</th>
    <th>Remarks</th>
    <th> ACTION </th>
    <th> ACTION </th>
  </tr>

  <% @user.todos.each do |todo| %>
      <tr>
        <td><%= todo.name.titleize %></td>
        <td><%= todo.remarks.titleize %></td>

        <td> <%= link_to "EDIT", edit_todo_path(todo.id), :class => 'btn btn-mini btn-warning' %> </td>
        <td> <%= link_to "DELETE", users_path, :class => 'btn btn-mini btn-danger' %> </td>
      </tr>
  <% end %>
</table>
</body>